name: "Website Healthcheck"
description: "Website status checking and text scanning"
branding:
  icon: activity
  color: white
inputs:
  maximum-retries:
    description: "Specify the maximum number of retries"
    required: true
  duration-between-retries:
    description: "Specify the duration between retries"
    required: true
  web-url:
    description: "Specify the URL to scan"
    required: true
  scan-for-text:
    description: "Specify the string that has to be scanned"
    required: true
runs:
  using: "composite"
  steps:
    - run: echo Scanning ${{ inputs.web-url }} for string ${{ inputs.scan-for-text }}
      shell: bash
    - run: chmod +x ${{ github.action_path }}/scan-website.sh
      shell: bash
    - run: ${{ github.action_path }}/scan-website.sh ${{ inputs.web-url }} ${{ inputs.scan-for-text }} $${{ inputs.maximum-retries }} $${{ inputs.duration-between-retries }}
      shell: bash
